### ISSUE TITLE
Psyche Boss not spawning in Ice Psyche Area & Issue with Water Psyche Boss

### ISSUE THREAD

**Issue by FlannelKat** [junglechief87/Seiren-Shuffle-An-Ys-8-Randomizer-#9] opened 2024-10-09 22:13 UTC
I was unable to complete a seed due to two different psyche spawns.

1) I was supposed to fight the insect psyche which would spawn in the Ice Psyche area. I had previously fought the ice psyche earlier so all that was in the arena was just the teleport out. It seemed no amount of waiting would ever pop the "presence" 

2) Alternatively I sought out the water psyche fight which was located in the pirate ship arena. I was able to spawn this one in the room adjacent to the arena and was able to fight the boss. However when I completed the boss instead of returning me to town like the others did it would spawn me in the ocean psyche area under the floor and unable to menu or do anything, essentially softlocked in place.

**Comment by junglechief87** [comment] 2024-10-09 22:26
Shoot me the spoiler. That will help me track down the issue faster. Thanks. Also, the eleftheria uses the entrance room instead of the boss arena because the boss arena technically becomes inaccessible after opening the chest there, I should note that in the readme. Thanks for the report

**Comment by FlannelKat** [comment] 2024-10-09 22:41
Here you go! 

Noted about eleftheria - that makes sense!


[Ys_8_4403345729098987.0.txt](https://github.com/user-attachments/files/17319482/Ys_8_4403345729098987.0.txt)

**Comment by junglechief87** [comment] 2024-10-09 23:48
What was the exact order you fought them? I think I might have found at least one of the issues, this might have possibly caused both. I just want to test in the same order.

**Comment by FlannelKat** [comment] 2024-10-09 23:54
Okay so first one I fought was the Psyche of the Frozen Era in the Mount Gendarme Boss Arena then the Psyche of the Sky in the Temple of the Great Tree.

As mentioned I was unable to spawn the psyche of the insectoid era inside the psyche of the ice era boss arena and then fought the psyche of the water era on eleftheria after clearing the pirate ship boss.

I also have my stream vod if you want to poke through that - I can find some timestamps. I did not fight the Water Era Psyche on stream but I can get a video of it if that would help!

**Comment by junglechief87** [comment] 2024-10-09 23:59
that's all really helpful, you don't have to dig that deep unless you want to. So the sequencing for the boss fight end event takes you through their area inside octus, though you wouldn't notice it because the screen is faded to black as it's executing the script there. I set a flag to prevent that brief moment from triggering any scripts. I thought I was flipping that flag back off once you hit castaway village... but whoops. I am pretty sure that caused the issue with the Nestor fight not triggering for you, I'm not sure if it could have caused the other issue.

**Comment by FlannelKat** [comment] 2024-10-10 00:07
My intuition is telling me its just loading back into the wrong area with a strange coordinate. I also think its loading a conversation because the only button that's doing anything is the the button to change how the text automatically progresses but no conversation is occurring. I'll grab a quick video of it and post it here.

**Comment by FlannelKat** [comment] 2024-10-10 00:11
Here's the vod of the softlock/freeze:

https://www.twitch.tv/videos/2272023815

**Comment by junglechief87** [comment] 2024-10-10 00:17
Yeah I reproduced the hydra issue, something is causing it to get stuck in the script. These sorts of issues can be pesky and it often ends up being some missing punctuation somewhere or something. 

It's specific to hydra too, I just flipped which boss was in that spot and it worked fine.

**Comment by junglechief87** [comment] 2024-10-10 00:37
Found the issue, it was trying to load two events at once when transitioning to the path of the ocean era. I will figure out a good fix. Probably tomorrow.

**Comment by FlannelKat** [comment] 2024-10-10 00:39
Awesome - thank you. I absolutely love the rando and appreciate you immensely for making this. Ys is an underexplored series for randomization and I honestly think 8 might be the best one to randomize. Potentially 9 also.

By the by - I had a few points of feedback I'd like to run by you. Is this the proper avenue for that?

**Comment by junglechief87** [comment] 2024-10-10 03:44
Thanks! Feel free.

**Comment by junglechief87** [comment] 2024-10-10 04:34
Issue should be fixed with new version

**Closed as completed** 2024-10-14 21:43 UTC
